# Generated by Django 4.2 on 2023-08-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exerciseinstanceinassignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
