# Generated by Django 4.2 on 2023-08-21 21:02

import core.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_submission_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Tiempo límite'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='hints',
            field=models.BooleanField(default=False, verbose_name='Mostrar casos de prueba'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='assignmentexercisegroup',
            name='count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Número de ejercicios'),
        ),
        migrations.AlterField(
            model_name='completedlevelsperuser',
            name='level',
            field=models.CharField(choices=[('facil', 'Facil'), ('media', 'Intermedio'), ('dificil', 'Dificil'), ('Completado', 'Completado')], default='Facil', max_length=20, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='completedlevelsperuser',
            name='skips',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Saltos disponibles'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='answer',
            field=models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Respuesta correcta'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='media', max_length=7, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CÓDIGO'), (1, 'OPCIÓN MÚLTIPLE')], default=0, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='explanation',
            field=models.CharField(blank=True, max_length=500, verbose_name='Explicación'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'RECHAZADO'), (1, 'EN REVISIÓN'), (2, 'ACEPTADO')], default=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='status_message',
            field=models.TextField(blank=True, default='', verbose_name='Mensaje del administrador'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='exercisechoice',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='exerciseinstanceinassignment',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Correcto?'),
        ),
        migrations.AlterField(
            model_name='exerciseinstanceinassignment',
            name='solution',
            field=models.TextField(verbose_name='Solución'),
        ),
        migrations.AlterField(
            model_name='exerciseinstanceingeneralpath',
            name='solution',
            field=models.TextField(verbose_name='Solución'),
        ),
        migrations.AlterField(
            model_name='exercisetestcase',
            name='expected_output',
            field=models.CharField(blank=True, max_length=500, validators=[core.models.validate_no_single_quotes], verbose_name='Resultado esperado'),
        ),
        migrations.AlterField(
            model_name='exercisetestcase',
            name='test_input',
            field=models.CharField(blank=True, max_length=500, validators=[core.models.validate_no_single_quotes], verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='start_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Tiempo de inicio'),
        ),
    ]
