# Generated by Django 4.2 on 2023-08-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_assignment_due_alter_assignment_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Tema'),
        ),
    ]
