# Generated by Django 4.2 on 2023-08-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentexercisegroup',
            name='exercise_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CÓDIGO'), (1, 'OPCIÓN MÚLTIPLE')], default=0, verbose_name='Tipo de ejercicios'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CÓDIGO'), (1, 'OPCIÓN MÚLTIPLE')], default=0, verbose_name='Tipo de ejercicio'),
        ),
    ]
