# Generated by Django 4.2 on 2023-08-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_assignmentexercisegroup_exercise_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='hints',
        ),
        migrations.AddField(
            model_name='assignment',
            name='feedback',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin retroalimentación'), (1, 'Mostrar cuántos casos de prueba pasaron'), (2, 'Mostrar detalles de cuáles casos de prueba pasaron')], default=1, verbose_name='Nivel de retroalimentación'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(verbose_name='Fecha de entrega'),
        ),
    ]
