# Generated by Django 4.2 on 2023-08-29 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Intentos permitidos'),
        ),
    ]
