# Generated by Django 4.2 on 2023-08-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_assignment_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Tiempo de entrega'),
        ),
    ]
