# Generated by Django 4.2 on 2023-08-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_submission_submit_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['submit_time']},
        ),
    ]
