# Generated by Django 4.2 on 2023-08-31 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_submission_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinstanceinassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='exerciseinstanceinassignment',
            name='user',
        ),
    ]
