# Generated by Django 4.2 on 2023-09-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_exerciseinstanceinassignment_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='Tema'),
        ),
    ]
