# Generated by Django 4.2 on 2023-09-06 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0002_alter_course_name'),
        ('core', '0016_alter_exercise_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='assignmentexercisegroup',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assignment', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='assignmentexercisegroup',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='completedlevelsperuser',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='completedlevelsperuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='exercisechoice',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.exercise', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='exerciseinstanceinassignment',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='exerciseinstanceinassignment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_instances', to='core.submission', verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='exerciseinstanceingeneralpath',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='exerciseinstanceingeneralpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='exercisetestcase',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.exercise', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assignment', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
    ]
