# Generated by Django 4.2 on 2023-09-21 03:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_assignment_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisechoice',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='exercisetestcase',
            name='expected_output',
            field=models.TextField(blank=True, max_length=500, validators=[core.models.validate_no_single_quotes], verbose_name='Resultado esperado'),
        ),
        migrations.AlterField(
            model_name='exercisetestcase',
            name='test_input',
            field=models.TextField(blank=True, max_length=500, validators=[core.models.validate_no_single_quotes], verbose_name='Entrada'),
        ),
    ]
