# Generated by Django 4.2 on 2023-10-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_exercisechoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstanceinassignment',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='¿Correcto?'),
        ),
    ]
