# Generated by Django 4.2 on 2023-08-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STUDENT'), (1, 'PROFESSOR')], default=1, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Cuenta verificada'),
        ),
    ]
