# Generated by Django 4.2 on 2023-08-21 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_last_name_alter_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9_!#$%&'*+\\/=?`{|}~^.-]+@tec\\.mx$", message='Ingresa un correo valido del Tecnologico de Monterrey')], verbose_name='Correo electrónico'),
        ),
    ]
